#!/usr/bin/env bash

echo "Running cache test..."

BUILD_DIR=$1
CACHE_DIR=$2
BUILD_PACK_DIR=$(dirname $(dirname $0))

echo "All arguments [$@]"

if [ ! -d "$BUILD_DIR" ]; then
  echo "Build directory [$BUILD_DIR] does not exist, creating"
  mkdir -p "$BUILD_DIR"
else
  echo "Build directory [$BUILD_DIR] exists"
  echo "Build directory contents..."
  ls -lRh $BUILD_DIR
fi

if [ ! -d "$CACHE_DIR" ]; then
  echo "Cache directory [$CACHE_DIR] does not exist, creating"
  mkdir -p "$CACHE_DIR"
else
  echo "Cache directory [$CACHE_DIR] exists"
fi

echo "The compile script is at [$0]"
echo "The build pack is situated at [$BUILD_PACK_DIR]"

echo "Moving to the cache dir..."
cd "$CACHE_DIR"
echo "Now in [$(pwd)]"

echo "Directory listing:"
ls -la

echo "Listing Build Pack Directory:"
ls -la /tmp/buildpacks

echo "Listing Build Pack Cache:"
ls -la "$BUILDPACK_CACHE"

echo "Listing Environment:"
env

echo "Listing OS Info:"
cat /etc/issue

echo "Listing script versions:"
python -V
echo
ruby -v
echo
perl -v

echo "User Limits:"
ulimit -a
echo

echo "Check for FUSE support"
/sbin/mount.fuse -h
ls -l /usr/share/doc/fuse-utils

echo "CPU Info"
cat /proc/cpuinfo

echo "Look for staging_info.yml file"
cat "$BUILD_DIR/staging_info.yml"

cd ../
echo "Creating start script"
cat > "$BUILD_DIR/start.sh" <<EOF
#!/bin/bash
#
# Download OpenJDK
mkdir openjdk/
cd openjdk/
wget http://download.run.pivotal.io/openjdk/mountainlion/x86_64/openjdk-1.8.0_25.tar.gz && tar -xvzf openjdk-1.8.0_25.tar.gz
cd ../
#export JAVA_HOME=pwd/openjdk-1.8.0_25/

# Download and start Tomcat container
mkdir tomcat/
cd tomcat/
wget http://download.run.pivotal.io/tomcat/tomcat-7.0.47.tar.gz && tar -xvzf tomcat-7.0.47.tar.gz
cd ../

# Download and install/start Apache HTTPd server
mkdir apache/
cd apache/
wget https://dl.dropbox.com/s/41fyqax01iqf0l7/apache_2.2.14_rh5_64.tar.gz && tar -xvzf apache_2.2.14_rh5_64.tar.gz
cd ../

wget https://ftp.gnu.org/gnu/libtool/libtool-1.5.6.tar.gz && tar -xvzf libtool-1.5.6.tar.gz
cd libtool-1.5.6/
./configure
make
make install

cd ../

wget http://sourceforge.net/projects/pcre/files/pcre/8.36/pcre-8.36.tar.gz && tar -xvzf pcre-8.36.tar.gz
cd pcre-8.36/
./configure --prefix=pwd/pcre
make
make install

cd ../

./configure --prefix=pwd/apache --with-included-apr --with-pcre=pwd/pcre/bin/pcre-config
make
make install
touch pwd/apache/logs/access_log
touch pwd/apache/logs/error_log
sh -x pwd/apache/bin/apachectl start
EOF
chmod 755 "$BUILD_DIR/start.sh"
